import type { IrDocumentV0 } from "./ir-v0.js";

export interface EmittedFile {
  readonly relativePath: string;
  readonly contents: string;
}

export interface EmitNextJsResult {
  readonly files: ReadonlyArray<EmittedFile>;
  readonly skipped: ReadonlyArray<{ readonly nodeId: string; readonly reason: string }>;
}

function nodeById(doc: IrDocumentV0): Map<string, IrDocumentV0["nodes"][number]> {
  return new Map(doc.nodes.map((n) => [n.id, n]));
}

/** Map IR route path to Next.js App Router file path (bronze stub handlers). */
export function routePathToAppRouterFile(path: string, method: string): string {
  const clean = path.replace(/\/$/, "") || "/";
  if (clean === "/") return `app/route.ts`;
  const segments = clean.split("/").filter(Boolean);
  return `app/${segments.join("/")}/route.ts`;
}

function handlerExportName(method: string): string {
  return method.toUpperCase();
}

function emitHandlerStub(method: string, path: string, source: string): string {
  const fn = handlerExportName(method);
  return [
    "// Generated by @wptp/emit-nextjs (bronze stub — replace with real logic)",
    `// Source: ${source}`,
    `// Route: ${method} ${path}`,
    "",
    `export async function ${fn}() {`,
    `  return Response.json({ ok: true, route: ${JSON.stringify(path)}, method: ${JSON.stringify(method)} });`,
    "}",
    "",
  ].join("\n");
}

/** Emit one route.ts per IR request/route node (bronze). */
export function emitNextJsAppRouter(doc: IrDocumentV0): EmitNextJsResult {
  const byId = nodeById(doc);
  const files = new Map<string, string>();
  const skipped: Array<{ nodeId: string; reason: string }> = [];

  for (const rootId of doc.roots) {
    const node = byId.get(rootId);
    if (!node) {
      skipped.push({ nodeId: rootId, reason: "root not in nodes" });
      continue;
    }
    if (node.layer !== "request" || node.op !== "route") {
      skipped.push({ nodeId: rootId, reason: `expected request/route, got ${node.layer}/${node.op}` });
      continue;
    }
    const path = typeof node.attrs.path === "string" ? node.attrs.path : null;
    const method = typeof node.attrs.method === "string" ? node.attrs.method : "GET";
    if (!path) {
      skipped.push({ nodeId: rootId, reason: "missing attrs.path" });
      continue;
    }
    const filePath = routePathToAppRouterFile(path, method);
    const source = doc.meta.importedFrom;
    const chunk = emitHandlerStub(method, path, source);
    const prev = files.get(filePath);
    files.set(filePath, prev ? `${prev}\n${chunk}` : chunk);
  }

  return {
    files: [...files.entries()].map(([relativePath, contents]) => ({ relativePath, contents })),
    skipped,
  };
}
